import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { createCanaryLineage,parsePropagation,PROPAGATION_HEADER } from '../src/sdk/index.js';
import { buildGraph,evaluatePolicies,exportBundle,importBundle } from '../src/analysis/index.js';
const key='test-only-shared-key-with-at-least-32-bytes';
const auth={activeKeyId:'current',keys:{current:key},requireSigned:true};
const input={synthetic:true,canaries:[{label:'email',value:'synthetic-only'}]};
const encode=c=>Buffer.from(JSON.stringify(c)).toString('base64url');
test('signed HTTP and delayed job context verify without unsigned trust override; raw values/keys stay out of exported evidence',async t=>{
  let child,header;
  const receiver=createCanaryLineage({serviceName:'receiver',distributed:true,failureMode:'strict',propagationAuthentication:auth});
  const server=createServer(async(req,res)=>{try{header=req.headers[PROPAGATION_HEADER];child=await receiver.run({...input,propagation:header},refs=>receiver.observe({type:'FUNCTION',location:'accept',canaries:refs}));res.end('ok');}catch{res.statusCode=500;res.end();}});
  server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(r=>server.close(r)));
  const origin=`http://127.0.0.1:${server.address().port}`;
  const source=createCanaryLineage({serviceName:'source',distributed:true,failureMode:'strict',propagationAuthentication:auth,allowedOrigins:[origin]});
  const parent=await source.run(input,refs=>source.http({url:origin,targetService:'receiver',canaries:refs}));await parent.result.body.cancel();assert.equal(parent.result.status,200);
  assert.equal(child.trace.propagationTrust,'verified');assert.equal(child.trace.id,parent.trace.id);
  const bundle=exportBundle([parent.trace,child.trace]);assert(!JSON.stringify(bundle).includes(key));assert(!Buffer.from(header,'base64url').toString().includes('synthetic-only'));
  assert.equal(evaluatePolicies(importBundle(bundle),{schemaVersion:1,rules:[{id:'trusted',type:'DENY_UNTRUSTED_PROPAGATION'}]}).status,'PASS');
  const job=await source.run(input,refs=>source.createJobContext({targetService:'receiver',canaries:refs}));
  const consumed=await receiver.run({...input,transport:'queue',propagation:job.result},()=>42);
  assert.equal(buildGraph([job.trace,consumed.trace]).complete,true);
});
test('authentication rejects tampering, unsigned downgrade, expiry, future time, unknown versions and wrong keys; supports rotation',async()=>{
  const source=createCanaryLineage({serviceName:'source',distributed:true,failureMode:'strict',propagationAuthentication:auth});
  const job=await source.run(input,refs=>source.createJobContext({targetService:'receiver',canaries:refs}));const envelope=JSON.parse(Buffer.from(job.result,'base64url'));
  for(const changed of [{...envelope,version:99},{...envelope,signature:'0'.repeat(64)},{...envelope,context:{...envelope.context,targetService:'attacker'}},{...envelope,keyId:'unknown'}])assert.throws(()=>parsePropagation(encode(changed),{authentication:auth}));
  assert.throws(()=>parsePropagation(job.result,{authentication:{...auth,keys:{current:'another-test-key-with-more-than-32-bytes'}}}));
  assert.throws(()=>parsePropagation(job.result,{authentication:auth,now:envelope.issuedAt+300001}));
  assert.throws(()=>parsePropagation(job.result,{authentication:auth,now:envelope.issuedAt-30001}));
  assert.throws(()=>parsePropagation(encode(envelope.context),{trusted:true,authentication:auth}));
  assert.equal(parsePropagation(job.result,{authentication:{activeKeyId:'next',keys:{current:key,next:'next-test-key-with-at-least-32-bytes'},requireSigned:true}}).authentication,'verified');
  const receiver=createCanaryLineage({serviceName:'receiver',distributed:true,propagationAuthentication:auth});
  const result=await receiver.run({...input,propagation:encode(envelope.context),trusted:true},()=>42);
  assert.equal(result.result,42);assert.equal(buildGraph(result.trace).evidence.state,'UNTRUSTED');assert.equal(evaluatePolicies(result.trace,{schemaVersion:1,rules:[]}).status,'FAIL');
  const strict=createCanaryLineage({serviceName:'receiver',distributed:true,failureMode:'strict',propagationAuthentication:auth});
  await assert.rejects(strict.run({...input,propagation:encode(envelope.context),trusted:true},()=>42),/Propagation rejected/);
  assert.throws(()=>createCanaryLineage({serviceName:'bad',propagationAuthentication:{...auth,keys:{current:'short'}}}));
});
test('evidence separates truncation, storage failure, unsigned context and pending events',async()=>{
  const bounded=createCanaryLineage({serviceName:'bounded',limits:{maxEvents:1}});
  const truncated=await bounded.run(input,refs=>{bounded.observe({type:'FUNCTION',location:'one',canaries:refs});bounded.observe({type:'FUNCTION',location:'two',canaries:refs});});
  assert.equal(buildGraph(truncated.trace).evidence.state,'TRUNCATED');
  const failed=createCanaryLineage({serviceName:'failed',storage:{getTrace:async()=>null,saveTrace:async()=>{throw Error('offline');}}});
  const partial=await failed.run(input,refs=>failed.observe({type:'FUNCTION',location:'work',canaries:refs}));assert.equal(buildGraph(partial.trace).evidence.state,'PARTIAL');
  const pending=structuredClone(partial.trace);pending.incomplete=false;pending.diagnostics=[];pending.events[0].status='pending';assert.equal(buildGraph(pending).complete,false);
  const source=createCanaryLineage({serviceName:'source',distributed:true});const job=await source.run(input,refs=>source.createJobContext({targetService:'target',canaries:refs}));
  const target=createCanaryLineage({serviceName:'target',distributed:true});const child=await target.run({...input,propagation:job.result,trusted:true,transport:'queue'},()=>42);
  const graph=buildGraph([job.trace,child.trace]);assert.equal(graph.complete,true);assert(graph.evidence.trust.includes('unsigned'));
  assert.equal(evaluatePolicies([job.trace,child.trace],{schemaVersion:1,rules:[{id:'trusted',type:'DENY_UNTRUSTED_PROPAGATION'}]}).status,'FAIL');
  const unsupported={...child.trace,schemaVersion:99};assert.throws(()=>buildGraph(unsupported));
});
